---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  is_file_root: true
  pillars:
    top.sls:
      base:
        '*':
          - threatstack
    threatstack.sls:
      deploy_key: <%= ENV['TS_DEPLOY_KEY'] != nil ? ENV['TS_DEPLOY_KEY'] : 'ts_deploy_key' %>
      ts_agent_version: <%= ENV['TS_PACKAGE_VERSION'] %>
      <% if ENV['TS_CONFIG_ARGS'] %>
      ts_agent_config_args: <%= ENV['TS_CONFIG_ARGS'] %>
      <% end %>
      ts_agent_version: <%= ENV['TS_PACKAGE_VERSION'] %>
  state_top:
    base:
      '*':
        - threatstack

platforms:
  - name: centos-6.7
  - name: debian-7.8
  - name: fedora-25
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
